<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: corelocation.proto

namespace Apple\CoreLocation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Apple.CoreLocation.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Apple.CoreLocation.Request.Router router = 2;</code>
     */
    private $router;
    /**
     * <code>int32 unknown3 = 3;</code>
     */
    private $unknown3 = 0;
    /**
     * <pre>
     * how many locations in response
     * </pre>
     *
     * <code>int32 amount = 4;</code>
     */
    private $amount = 0;

    public function __construct() {
        \GPBMetadata\Corelocation::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .Apple.CoreLocation.Request.Router router = 2;</code>
     */
    public function getRouter()
    {
        return $this->router;
    }

    /**
     * <code>repeated .Apple.CoreLocation.Request.Router router = 2;</code>
     */
    public function setRouter(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Apple\CoreLocation\Request_Router::class);
        $this->router = $arr;
    }

    /**
     * <code>int32 unknown3 = 3;</code>
     */
    public function getUnknown3()
    {
        return $this->unknown3;
    }

    /**
     * <code>int32 unknown3 = 3;</code>
     */
    public function setUnknown3($var)
    {
        GPBUtil::checkInt32($var);
        $this->unknown3 = $var;
    }

    /**
     * <pre>
     * how many locations in response
     * </pre>
     *
     * <code>int32 amount = 4;</code>
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * <pre>
     * how many locations in response
     * </pre>
     *
     * <code>int32 amount = 4;</code>
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->amount = $var;
    }

}
