<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: corelocation.proto

namespace Apple\CoreLocation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Apple.CoreLocation.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Apple.CoreLocation.Response.Container wifi = 2;</code>
     */
    private $wifi;

    public function __construct() {
        \GPBMetadata\Corelocation::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .Apple.CoreLocation.Response.Container wifi = 2;</code>
     */
    public function getWifi()
    {
        return $this->wifi;
    }

    /**
     * <code>repeated .Apple.CoreLocation.Response.Container wifi = 2;</code>
     */
    public function setWifi(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Apple\CoreLocation\Response_Container::class);
        $this->wifi = $arr;
    }

}

